=== DuarteOlival99/Aplica-es-na-Web-project/businessObjects/perfilSchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "firstname": {
        "type": "string"
      },
      "lastname": {
        "type": "string"
      },
      "age": {
        "type": "integer"
      },
      "gender": {
        "type": "string"
      },
      "birthday": {
        "type": "string"
      },
      "phone": {
        "type": "string"
      },
      "photo": {
        "type": "string"
      },
      "location": {
        "type": "object",
        "properties": {
          "city": {
            "type": "string"
          },
          "state": {
            "type": "string"
          }
        },
        "required": [
          "city",
          "state"
        ]
      },
      "about": {
        "type": "string"
      },
      "messages": {
        "type": "array",
        "items": [
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "textmessage": {
                "type": "array",
                "items": [
                  {
                    "type": "object",
                    "properties": {
                      "date": {
                        "type": "string"
                      },
                      "text": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "date",
                      "text"
                    ]
                  }
                ]
              }
            },
            "required": [
              "id",
              "name",
              "textmessage"
            ]
          },
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "textmessage": {
                "type": "array",
                "items": [
                  {
                    "type": "object",
                    "properties": {
                      "date": {
                        "type": "string"
                      },
                      "text": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "date",
                      "text"
                    ]
                  }
                ]
              }
            },
            "required": [
              "id",
              "name",
              "textmessage"
            ]
          },
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "textmessage": {
                "type": "array",
                "items": [
                  {
                    "type": "object",
                    "properties": {
                      "date": {
                        "type": "string"
                      },
                      "text": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "date",
                      "text"
                    ]
                  }
                ]
              }
            },
            "required": [
              "id",
              "name",
              "textmessage"
            ]
          },
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "textmessage": {
                "type": "array",
                "items": [
                  {
                    "type": "object",
                    "properties": {
                      "date": {
                        "type": "string"
                      },
                      "text": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "date",
                      "text"
                    ]
                  }
                ]
              }
            },
            "required": [
              "id",
              "name",
              "textmessage"
            ]
          }
        ]
      },
      "publications": {
        "type": "array",
        "items": {}
      }
    },
    "required": [
      "id",
      "firstname",
      "lastname",
      "age",
      "gender",
      "birthday",
      "phone",
      "photo",
      "location",
      "about",
      "messages",
      "publications"
    ]
  }

=== DuarteOlival99/Aplica-es-na-Web-project/businessObjects/perfil.json
{
  "id": 1,
  "firstname": "Donald",
  "lastname": "Trump",
  "age": 74,
  "gender": "male",
  "birthday": "14/06/1946",
  "phone": "987654321",
  "photo":"eff60af78d1ded9d62fcff68f84370ee", 
  "location": {
    "city": "Lisboa",
    "state": "PT"
  }, 
  "about":"alguma coisa sobre a pessoa", 
  "messages": [
    {
      "messagesID": 1
    }, 
    {
      "messagesID": 2
    }, 
    {
      "messagesID": 3
    },
    {
      "messagesID": 4
    }
  ],
  "publications": [
    {
      "publicationsID": 1
    },
    {
      "publicationsID": 5
    }
  ]
}
