=== DuarteOlival99/Aplica-es-na-Web-project/businessObjects/publicacoesSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "firstname": {
      "type": "string"
    },
    "lastname": {
      "type": "string"
    },
    "photoUser": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "publicationPhoto": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "firstname",
    "lastname",
    "photoUser",
    "description",
    "date",
    "publicationPhoto"
  ]
}

=== DuarteOlival99/Aplica-es-na-Web-project/businessObjects/publicacoes.json
{
  "id": 1, 
  "firstname": "Donald",
  "lastname": "Trump",
  "photoUser":"eff60af78d1ded9d62fcff68f84370ee", 
  "description": "This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.",
  "date": "15/04/2021",
  "publicationPhoto":"96a3be3cf272e017046d1b2674a52bd3"
}
